services:
  database:
    container_name: mysql-agrominas
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${AGROMINAS_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${AGROMINAS_DATABASE_NAME}
      MYSQL_USER: ${AGROMINAS_DATABASE_USER}
      MYSQL_PASSWORD: ${AGROMINAS_DATABASE_PASSWORD}
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
