services:
  database:
    container_name: postgres-agrominas
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${AGROMINAS_DATABASE_PASSWORD}
      POSTGRES_DB: ${AGROMINAS_DATABASE_NAME}
      POSTGRES_USER: ${AGROMINAS_DATABASE_USER}
      PGDATA: /data/postgres
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
