name: Deploy para EC2 Windows IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Buildar projeto (se necessário)
        run: |
          npm install
          npm run build

      - name: Copiar arquivos via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.WIN_EC2_HOST }}
          username: ${{ secrets.WIN_EC2_USER }}
          password: ${{ secrets.WIN_EC2_SSH_KEY }}
          port: 22
          source: "."
          target: "C:/deploy/app"

      - name: Executar script de deploy remoto via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.WIN_EC2_HOST }}
          username: ${{ secrets.WIN_EC2_USER }}
          password: ${{ secrets.WIN_EC2_SSH_KEY }}
          port: 22
          script: |
            powershell.exe "C:\deploy\app\restart-app.ps1"
